### ISSUE TITLE
套warp版本不可用

### ISSUE THREAD

**Issue by stoneaw** [vveg26/chromego_merge#18]
始终是出错信息，试了好多次都不行。

**Comment by vveg26** [comment]
我这边没问题，提供一下出错信息

**Comment by vveg26** [comment]
> ![Screenshot_20231108_173621](https://user-images.githubusercontent.com/33226958/281348863-c705c51b-e1a6-4eab-a647-79b1c3c21442.jpg) 我试了ClashMeta安卓版和windows版都不行，一直出错，但是那个不套warp的[https://mareep.netlify.app/sub/merged_proxies_new.yaml可以正常使用。](https://mareep.netlify.app/sub/merged_proxies_new.yaml%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8%E3%80%82)
> 
> 套warp的[https://mareep.netlify.app/sub/merged_warp_proxies_new.yaml在nekobox安卓版可以变通之后使用，先按照订阅链接导入，根本就没有wireguard这一项，我把wireguard单独用另外的办法导入，然后手动输入，选择链式代理，第1项任选一个比较快的代理，第2项选择新建的wireguard，这样就可以使用了。](https://mareep.netlify.app/sub/merged_warp_proxies_new.yaml%E5%9C%A8nekobox%E5%AE%89%E5%8D%93%E7%89%88%E5%8F%AF%E4%BB%A5%E5%8F%98%E9%80%9A%E4%B9%8B%E5%90%8E%E4%BD%BF%E7%94%A8%EF%BC%8C%E5%85%88%E6%8C%89%E7%85%A7%E8%AE%A2%E9%98%85%E9%93%BE%E6%8E%A5%E5%AF%BC%E5%85%A5%EF%BC%8C%E6%A0%B9%E6%9C%AC%E5%B0%B1%E6%B2%A1%E6%9C%89wireguard%E8%BF%99%E4%B8%80%E9%A1%B9%EF%BC%8C%E6%88%91%E6%8A%8Awireguard%E5%8D%95%E7%8B%AC%E7%94%A8%E5%8F%A6%E5%A4%96%E7%9A%84%E5%8A%9E%E6%B3%95%E5%AF%BC%E5%85%A5%EF%BC%8C%E7%84%B6%E5%90%8E%E6%89%8B%E5%8A%A8%E8%BE%93%E5%85%A5%EF%BC%8C%E9%80%89%E6%8B%A9%E9%93%BE%E5%BC%8F%E4%BB%A3%E7%90%86%EF%BC%8C%E7%AC%AC1%E9%A1%B9%E4%BB%BB%E9%80%89%E4%B8%80%E4%B8%AA%E6%AF%94%E8%BE%83%E5%BF%AB%E7%9A%84%E4%BB%A3%E7%90%86%EF%BC%8C%E7%AC%AC2%E9%A1%B9%E9%80%89%E6%8B%A9%E6%96%B0%E5%BB%BA%E7%9A%84wireguard%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E4%BA%86%E3%80%82)
> 
> 目前我只使用过这几个客户端是这个情况，请问你是用的什么客户端？

我在macOS的clash verge和clashX.meta中使用并没有报错，你没有给出具体的meta报错信息，链式代理我只写了meta客户端的，其他的客户端还是要手动操作一下，主要是不方便导入。
![](https://img.mareep.net/blog/2023/11/4b9f25e6669098b5d091246c371a5913.png)

**Comment by vveg26** [comment]
> clash-verge nekobox似乎不支持wg协议，小火箭没法搞链式代理，所以只能安卓玩玩了？🤣

前两个客户端支持wg的，小火箭没试过，可能不行

**Comment by vveg26** [comment]
> windows端meta的报错信息： time="2023-11-08T22:03:31.498843+08:00" level=warning msg="[TCP] dial 节点选择 (match Match/) 127.0.0.1:54230 --> [www.google.com:443](http://www.google.com:443) error: a:1 connect error: dns resolve failed: couldn't find ip" 等了好几分钟，一直都是这样的信息。如果把 油管-绵阿羊 删除，则wg的dialer-proxy使用meta_tuic_01（并不查找延迟最低的），一般可以连通。

![](https://img.mareep.net/blog/2023/11/9d34fa247966af1fbc07cff9c8f914ea.png)
可以切换warp的前置节点为手动选择，有空我把油管-绵阿羊这个东西删了

**Comment by vveg26** [comment]
> > > clash-verge nekobox似乎不支持wg协议，小火箭没法搞链式代理，所以只能安卓玩玩了？🤣
> > 
> > 
> > 前两个客户端支持wg的，小火箭没试过，可能不行
> 
> 刚才又试了下，你提供的warp节点在clash-verge里一直超时， 然后nekobox不能直接粘贴wg:格式的节点，但是用nekobox拼接一个2级链式代理就行了。具体做法是新建一个链式代理，第一级用chromego的大带宽节点，二级拼接一个自己的CF节点， 这样能跑满带宽+解锁被chromego屏蔽的网站

可以这样，理论上链一个没封锁策略的节点就行了，warp主要还是因为免费所以我链着

**Comment by vveg26** [comment]
> 小火箭，clash 都可以正常使用，谢谢大神，不过修改自己的 warp 更新后就又恢复成初始的了。

可以试试proxy-providers
