### ISSUE TITLE
doesnot work properly after update

### ISSUE THREAD

**Issue by jasonhoo1999** [vveg26/chromego_merge#2]
unsupport proxy type hysteria 2

**Comment by vveg26** [comment]
use the latest version of the Meta kernel or update your client kernel to the latest version of the Meta kernel at https://github.com/MetaCubeX/Clash.Meta/releases/tag/v1.16.0.

**Comment by vveg26** [comment]
I have already deleted the Hysteria2 node.

**Comment by jasonhoo1999** [comment]
Thank you very much for the reply and the update
Sent from Gmail Mobile


mareep ***@***.***>于2023年9月27日 周三16:12写道：
