### ISSUE TITLE
“Warp前置节点”使用”自动选择“与“手动选择”时，"自动"比较不稳定，似乎不是每个节点都能顺利套上warp，这是什么原因?

### ISSUE THREAD

**Issue by su2353** [vveg26/chromego_merge#22]
是warp配置不行，还是前置节点有问题，求解

**Comment by vveg26** [comment]
前置节点的问题

**Comment by su2353** [comment]
有解决方法吗？

**Comment by vveg26** [comment]
我没找到好的方法

**Comment by onlyno999** [comment]
负债均衡 轮询模式比较稳当一些。

**Comment by onlyno999** [comment]
我告诉你是什么问题，因为是人家很多远程服务器，根本都不支持远程解析。只需要把这些删掉就可以了。
- name: WARP
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  ip: 172.16.0.2
  ipv6: 2606:4700:110:87c0:ba32:773a:8d44:e353
  private-key: +HpHpY/KjSv5hJdGrN2ok1A6CKhCmTQv5Unwyul9S1g=
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  dialer-proxy: WARP前置节点

**Comment by onlyno999** [comment]
> > 我告诉你是什么问题，因为是人家很多远程服务器，根本都不支持远程解析。只需要把这些删掉就可以了。
> > 
> > * name: WARP
> >   type: wireguard
> >   server: engage.cloudflareclient.com
> >   port: 2408
> >   ip: 172.16.0.2
> >   ipv6: 2606:4700:110:87c0:ba32:773a:8d44:e353
> >   private-key: +HpHpY/KjSv5hJdGrN2ok1A6CKhCmTQv5Unwyul9S1g=
> >   public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
> >   dialer-proxy: WARP前置节点
> 
> 可即使连接上了,一会儿也会掉,一会又连上,就是不稳


我给你提供一个思路。 前置节点。复制出来七道八个，前置节点设置为负载均衡轮询，稳如老狗。
![Uploading Screenshot_2023-12-08-15-16-46-127_com.github.metacubex.clash.meta.jpg…]()

**Comment by su2353** [comment]
![image](https://github.com/vveg26/chromego_merge/assets/35580211/25b1c174-d20c-4ab6-bc20-9ab66d93fc6c)
这样吗?
