### ISSUE TITLE
老板来回答个问题。

### ISSUE THREAD

**Issue by onlyno999** [vveg26/chromego_merge#24]
https://sing-box-subscribe.vercel.app/config/添加节点地址。
用这个转出来。所有的节点。为啥都看不了p站？

**Comment by vveg26** [comment]
chromego的节点服务器上屏蔽了大部分18禁网站，解决办法要么用链式代理比如套个warp，要么浏览器上开doh绕过

**Comment by onlyno999** [comment]
我说用你提供的这个转换器。转换其他的节点也同样的被屏蔽掉了。

**Comment by vveg26** [comment]
这个一般来说不会出现这种情况。你去看看他的分流对不对，我记得他默认配置是更新到了1.8.0，规则集格式变了

**Comment by Toperlock** [comment]
> [https://sing-box-subscribe.vercel.app/config/添加节点地址。](https://sing-box-subscribe.vercel.app/config/%E6%B7%BB%E5%8A%A0%E8%8A%82%E7%82%B9%E5%9C%B0%E5%9D%80%E3%80%82) 用这个转出来。所有的节点。为啥都看不了p站？

请您动动手策略组选择一个节点

https://github.com/Toperlock/sing-box-subscribe/assets/86833913/5df6df19-edef-436d-97e9-83679dfeac17
