### ISSUE TITLE
sing-box 订阅error

### ISSUE THREAD

**Issue by drunkbear999** [vveg26/chromego_merge#25]
谢谢，明白了，我的iOS的版本只有1.7.2

**Comment by vveg26** [comment]
用的别人的订阅转换，"rule_set"需要singbox1.8.0以上支持
https://github.com/Toperlock/sing-box-subscribe#sing-box-180-已发布配置需要修改已上传rule_set模板并且默认生成最新配置文件适配-sing-box-180用旧版singbox请选择config_template_groups_tunjson模板

**Comment by onlyno999** [comment]
> 使用别人的订阅转换，“rule_set”需要singbox1.8.0以上支持 [https://github.com/Toperlock/sing-box-subscribe#sing-box-180-已发布配置需要修改已生成上传rule_set模板并且默认最新配置文件架构-sing-box-180用旧版本singbox请选择config_template_groups_tunjson模板](https://github.com/Toperlock/sing-box-subscribe#sing-box-180-%E5%B7%B2%E5%8F%91%E5%B8%83%E9%85%8D%E7%BD%AE%E9%9C%80%E8%A6%81%E4%BF%AE%E6%94%B9%E5%B7%B2%E4%B8%8A%E4%BC%A0rule_set%E6%A8%A1%E6%9D%BF%E5%B9%B6%E4%B8%94%E9%BB%98%E8%AE%A4%E7%94%9F%E6%88%90%E6%9C%80%E6%96%B0%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E9%80%82%E9%85%8D-sing-box-180%E7%94%A8%E6%97%A7%E7%89%88singbox%E8%AF%B7%E9%80%89%E6%8B%A9config_template_groups_tunjson%E6%A8%A1%E6%9D%BF)

导入提示出现。安卓最新版1.8 不管开代理不开代理都会出现这个。

Error parse outbound[33]:unknown congestion control algorithm:bb 确定

**Comment by vveg26** [comment]
https://github.com/vveg26/chromego_merge/issues/27#issuecomment-1848941999
