### ISSUE TITLE
连接代理失败

### ISSUE THREAD

**Issue by lyc452** [vveg26/chromego_merge#26]
只在手机上遇到，不知道是软件的问题还是订阅的问题，两边都问问。
详情https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/470

**Comment by onlyno999** [comment]
sing-box上面也是这样子的。clash没问题

**Comment by vveg26** [comment]
母鸡

**Comment by lyc452** [comment]
见鬼了，过了几天莫名其妙的好了，但以后会不会在来一次不好说
