### ISSUE TITLE
订阅拉取出错

### ISSUE THREAD

**Issue by qaz617** [vveg26/chromego_merge#27]
https://github.com/vveg26/chromego_merge/blob/4bcc88cf0ab5d1370f146d45d803e36655098fff/sub/merged_proxies_new.yaml#L138
应修改为`bbr`

**Comment by vveg26** [comment]
移除了
https://github.com/Alvin9999/pac2/commit/5e3468e1d05c2c80a34aa7ad86895b3d2aeab1b7#diff-873ade6a891e9e9f9cce1400638c4978f1a9b7072e765fb42bd1ea502aed7996
